In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel('all.xlsx')

In [3]:
df

,Reference,ItemNameType,SerialNumber,ProductName,Button1_F1,Button1_F2,Button1_ClickRatio,Button1_Stroke,Button2_F1,Button2_F2,...,Button3_Stroke,Button4_F1,Button4_F2,Button4_ClickRatio,Button4_Stroke,Button5_F1,Button5_F2,Button5_ClickRatio,Button5_Stroke,tDateTime
0,401004655,12434,3422062003,"Sub-Assy, Top Unit, Magna, Golfer",6.30,4.73,0.25,0.40,6.27,4.63,...,0.39,6.45,4.77,0.25,0.26,6.26,4.64,0.27,0.33,2022-07-22 11:02:12
1,401005050,12434,3422062000,"Sub-Assy, Top Unit, Magna, Golfer",6.19,4.64,0.26,0.32,6.16,4.55,...,0.32,7.42,5.78,0.22,0.49,6.32,4.60,0.27,0.23,2022-07-22 11:03:53
2,401005378,12434,3422062034,"Sub-Assy, Top Unit, Magna, Golfer",6.33,4.80,0.24,0.32,6.50,4.75,...,0.27,7.06,5.35,0.25,0.52,6.36,4.75,0.27,0.26,2022-07-22 11:05:37
3,401005756,12434,3422061999,"Sub-Assy, Top Unit, Magna, Golfer",6.37,4.68,0.27,0.44,6.13,4.56,...,0.32,6.41,4.81,0.25,0.27,6.48,5.09,0.22,0.26,2022-07-22 11:07:28
4,401006101,12434,3422062018,"Sub-Assy, Top Unit, Magna, Golfer",6.19,4.60,0.26,0.29,6.16,4.51,...,0.37,6.37,4.73,0.27,0.31,6.45,4.79,0.25,0.29,2022-07-22 11:09:01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
531,403822567,12434,3425559216,"Sub-Assy, Top Unit, Magna, Aviator",6.11,4.42,0.28,0.26,6.67,4.90,...,0.38,6.92,5.05,0.28,0.35,6.15,4.53,0.27,0.29,2022-08-11 01:56:05
532,403822985,12434,3425559236,"Sub-Assy, Top Unit, Magna, Aviator",6.41,4.72,0.27,0.42,6.49,4.74,...,0.38,7.31,5.24,0.29,0.37,6.67,5.02,0.25,0.33,2022-08-11 01:58:15
533,405707886,12434,3422062319,"Sub-Assy, Top Unit, Magna, Athlete",6.38,4.88,0.23,0.38,6.45,4.86,...,0.37,6.41,4.82,0.25,0.36,6.41,4.89,0.23,0.26,2022-08-25 00:49:21
534,405709836,12434,3422062319,"Sub-Assy, Top Unit, Magna, Athlete",6.09,4.52,0.26,0.36,6.35,4.69,...,0.36,6.33,4.68,0.25,0.34,6.06,4.43,0.28,0.29,2022-08-25 01:04:39
535,405710597,12434,3422062319,"Sub-Assy, Top Unit, Magna, Athlete",6.11,4.56,0.25,0.35,6.35,4.79,...,0.37,6.28,4.58,0.27,0.34,5.98,4.38,0.27,0.26,2022-08-25 01:11:09

In [18]:
col_F1F2 = df.columns[df.columns.str.contains('F1|F2')]
col_F1F2

Index(['Button1_F1', 'Button1_F2', 'Button2_F1', 'Button2_F2', 'Button3_F1',
       'Button3_F2', 'Button4_F1', 'Button4_F2', 'Button5_F1', 'Button5_F2'],
      dtype='object')

In [21]:
col_click = df.columns[df.columns.str.contains('ClickRatio')]
col_click

Index(['Button1_ClickRatio', 'Button2_ClickRatio', 'Button3_ClickRatio',
       'Button4_ClickRatio', 'Button5_ClickRatio'],
      dtype='object')

In [71]:
goodsample = df[(df['Button1_ClickRatio']>0.2) & (df['Button2_ClickRatio']>0.2) & (df['Button3_ClickRatio']>0.2) & (df['Button4_ClickRatio']>0.2) & (df['Button5_ClickRatio']>0.2)]

In [74]:
goodsample[col_F1F2].describe()

,Button1_F1,Button1_F2,Button2_F1,Button2_F2,Button3_F1,Button3_F2,Button4_F1,Button4_F2,Button5_F1,Button5_F2
count,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000,402.000000
mean,6.409701,4.779900,6.450970,4.787139,6.730622,5.085846,6.888010,5.194527,6.531567,4.921269
std,0.312344,0.325834,0.214656,0.199868,0.370282,0.300376,0.596383,0.493956,0.255887,0.244722
min,5.930000,4.280000,6.060000,4.390000,5.980000,4.320000,6.040000,4.400000,5.980000,4.380000
25%,6.190000,4.540000,6.330000,4.670000,6.500000,4.880000,6.510000,4.872500,6.360000,4.750000
50%,6.290000,4.670000,6.420000,4.770000,6.645000,5.050000,6.700000,5.055000,6.500000,4.910000
75%,6.577500,4.927500,6.520000,4.880000,6.907500,5.270000,7.047500,5.380000,6.657500,5.060000
max,7.450000,5.860000,7.590000,5.890000,8.910000,6.870000,9.330000,7.140000,7.750000,5.900000

: