In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
project_list_file = 'ProjectListExport_2022-05-20-09-13-56-082.xls'
cft_list_file = 'CFTListExport_2022-05-20-09-10-10-246.xls'

In [53]:
project = pd.read_excel(project_list_file, usecols=[0,1,3,4,5,6,9,10], parse_dates=[2,3,4,5])
cft = pd.read_excel(cft_list_file, usecols=[0,44])

c:\Users\wangcooper\Anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:221: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [38]:
cft

      Project ID Develop  Product QE (DPQE)
0          13939                 Kuo, Chris
1          15274                 Kuo, Chris
2          15624                  Lo, Aalto
3          13009                 Kuo, Chris
4          14984                 Kuo, Chris
...          ...                        ...
3087        7141               Wang, Cooper
3088        2358                        NaN
3089        2542                        NaN
3090        2263                        NaN
3091        2333                        NaN

[3092 rows x 2 columns]

In [55]:
project = project[(project['Global/Asia'] == 'Global') & (project['PDP/Form107'] == 'PDP')]
project

,Project ID,Project Name,Working Prototype Built and Tested,Final Factory Prototypes Built,MP Date,PR Date,Global/Asia,PDP/Form107
0,13939,BC50 & BC50 Night Vision,2021-08-20,NaT,2022-04-25,2022-01-04,Global,PDP
2,15624,Catalyst Kart/Moto/Roadster,2022-06-24,2022-10-10,2023-03-06,2022-12-29,Global,PDP
3,13009,Dash Cam Live (LTE),2021-06-25,2022-03-11,2022-09-12,2022-07-13,Global,PDP
5,13139,Dezl Headset,2021-06-18,2021-10-15,2022-03-21,2022-01-03,Global,PDP
6,15861,dezl OTR Series 2022,2021-11-18,2022-01-14,2022-05-09,2022-03-15,Global,PDP
...,...,...,...,...,...,...,...,...
372,12040,Tempe 2,NaT,NaT,NaT,NaT,Global,PDP
373,15988,Xero A2i Bow Sight,NaT,NaT,NaT,NaT,Global,PDP
374,16048,Xero G1c Photo Transmitting Cellular Scouting ...,NaT,NaT,NaT,NaT,Global,PDP
375,13239,Xero P60i Laser Spotting Scope,NaT,NaT,NaT,NaT,Global,PDP
376,15990,Xero X1s Crossbow Scope,NaT,NaT,NaT,NaT,Global,PDP

In [65]:
project_cft = pd.merge(left=project, right=cft)
project_cft

,Project ID,Project Name,Working Prototype Built and Tested,Final Factory Prototypes Built,MP Date,PR Date,Global/Asia,PDP/Form107,Develop Product QE (DPQE)
0,13939,BC50 & BC50 Night Vision,2021-08-20,NaT,2022-04-25,2022-01-04,Global,PDP,"Kuo, Chris"
1,15624,Catalyst Kart/Moto/Roadster,2022-06-24,2022-10-10,2023-03-06,2022-12-29,Global,PDP,"Lo, Aalto"
2,13009,Dash Cam Live (LTE),2021-06-25,2022-03-11,2022-09-12,2022-07-13,Global,PDP,"Kuo, Chris"
3,13139,Dezl Headset,2021-06-18,2021-10-15,2022-03-21,2022-01-03,Global,PDP,"Ni, Wendy"
4,15861,dezl OTR Series 2022,2021-11-18,2022-01-14,2022-05-09,2022-03-15,Global,PDP,"Ni, Wendy"
...,...,...,...,...,...,...,...,...,...
301,12040,Tempe 2,NaT,NaT,NaT,NaT,Global,PDP,"Kuo, Chris"
302,15988,Xero A2i Bow Sight,NaT,NaT,NaT,NaT,Global,PDP,NaN
303,16048,Xero G1c Photo Transmitting Cellular Scouting ...,NaT,NaT,NaT,NaT,Global,PDP,NaN
304,13239,Xero P60i Laser Spotting Scope,NaT,NaT,NaT,NaT,Global,PDP,"Kuo, Chris"
305,15990,Xero X1s Crossbow Scope,NaT,NaT,NaT,NaT,Global,PDP,NaN

In [66]:
project_cft.columns

Index(['Project ID', 'Project Name', 'Working Prototype Built and Tested',
       'Final Factory Prototypes Built', 'MP Date', 'PR Date', 'Global/Asia',
       'PDP/Form107', 'Develop  Product QE (DPQE)'],
      dtype='object')

In [67]:
project_cft['Develop  Product QE (DPQE)'].unique()

array(['Kuo, Chris', 'Lo, Aalto', 'Ni, Wendy', 'Hsu, Jason(PQE)', nan,
       'Dong, Reta', 'Fu, Ernest', 'Fu, Ernest;\nLo, Aalto',
       'Chen, Tiffany(QA);\nPuder, Kristi;\nKelly, Joan;\nSantos, Mila;\nHolland, Wendy;\nBennett, Travis;\nTugui, Susanne;\nSauer, Stefanie;\nBruns, Melanie;\nChen, Allen;\nTsai, Cherry',
       'Chen, Tiffany(QA);\nKelly, Joan;\nBruns, Melanie;\nKocon, Andy;\nYamnitz, Ryan;\nJundi, Ramzi;\nOverzier, Martin;\nKeller, Marina;\nHu, Ray;\nHu, Ray;\nTsai, Cherry;\nHsu, Jessie',
       'Tsai, Cherry;\nPeranovic, Predrag;\nNefzger, Bernadette;\nKelly, Joan;\nPinte, Marius;\nJones, Rachel;\nYamnitz, Ryan;\nBruns, Melanie',
       'Not Applicable', 'Chen, Tiffany(QA);\nYu, Arthur', 'Yu, Arthur',
       'Hsu, Jin', 'Tsai, Abner', 'Wang, Cooper',
       'Wang, Cooper;\nNi, Wendy'], dtype=object)

In [64]:
consumer_dpqe_list = ['Lo, Aalto','Kuo, Chris','Wang, Cooper', 'Fu, Ernest','Fu, Ernest;\nLo, Aalto','Hsu, Jason(PQE)','Ni, Wendy']

In [70]:
df_consumer_dpqe = project_cft[project_cft['Develop  Product QE (DPQE)'].isin(consumer_dpqe_list)]
df_consumer_dpqe

,Project ID,Project Name,Working Prototype Built and Tested,Final Factory Prototypes Built,MP Date,PR Date,Global/Asia,PDP/Form107,Develop Product QE (DPQE)
0,13939,BC50 & BC50 Night Vision,2021-08-20,NaT,2022-04-25,2022-01-04,Global,PDP,"Kuo, Chris"
1,15624,Catalyst Kart/Moto/Roadster,2022-06-24,2022-10-10,2023-03-06,2022-12-29,Global,PDP,"Lo, Aalto"
2,13009,Dash Cam Live (LTE),2021-06-25,2022-03-11,2022-09-12,2022-07-13,Global,PDP,"Kuo, Chris"
3,13139,Dezl Headset,2021-06-18,2021-10-15,2022-03-21,2022-01-03,Global,PDP,"Ni, Wendy"
4,15861,dezl OTR Series 2022,2021-11-18,2022-01-14,2022-05-09,2022-03-15,Global,PDP,"Ni, Wendy"
...,...,...,...,...,...,...,...,...,...
296,14604,L20 Laser Range Finder,NaT,NaT,NaT,NaT,Global,PDP,"Kuo, Chris"
297,12716,LIDAR-Lite V4 Laser,NaT,NaT,NaT,NaT,Global,PDP,"Kuo, Chris"
300,12279,Marq Hybrid,NaT,NaT,NaT,NaT,Global,PDP,"Wang, Cooper"
301,12040,Tempe 2,NaT,NaT,NaT,NaT,Global,PDP,"Kuo, Chris"
304,13239,Xero P60i Laser Spotting Scope,NaT,NaT,NaT,NaT,Global,PDP,"Kuo, Chris"

In [72]:
df_consumer_dpqe.groupby(['Develop  Product QE (DPQE)','Project Name']).count()

                                                         Project ID  \
Develop  Product QE (DPQE) Project Name
Fu, Ernest                 2022 vivofit jr. 3 SKUs                1
                           Bounce                                 1
                           Forerunner 255 Small                   1
                           Forerunner 255 and 255 Music           1
                           Forerunner 265                         1
...                                                             ...
Wang, Cooper               Enduro 2023                            1
                           Marq Hybrid                            1
                           fenix 7 Pro                            1
                           fenix 7S Pro                           1
                           fenix 7X Pro                           1

                                                         Working Prototype Built and Tested  \
Develop  Product QE (DPQE) Project Name
Fu, Ernest                 2022 vivofit jr. 3 SKUs                                        0
                           Bounce                                                         0
                           Forerunner 255 Small                                           0
                           Forerunner 255 and 255 Music                                   1
                           Forerunner 265                                                 1
...                                                                                     ...
Wang, Cooper               Enduro 2023                                                    1
                           Marq Hybrid                                                    0
                           fenix 7 Pro                                                    1
                           fenix 7S Pro                                                   1
                           fenix 7X Pro                                                   1

                                                         Final Factory Prototypes Built  \
Develop  Product QE (DPQE) Project Name
Fu, Ernest                 2022 vivofit jr. 3 SKUs                                    1
                           Bounce                                                     1
                           Forerunner 255 Small                                       0
                           Forerunner 255 and 255 Music                               1
                           Forerunner 265                                             1
...                                                                                 ...
Wang, Cooper               Enduro 2023                                                0
                           Marq Hybrid                                                0
                           fenix 7 Pro                                                1
                           fenix 7S Pro                                               1
                           fenix 7X Pro                                               1

                                                         MP Date  PR Date  \
Develop  Product QE (DPQE) Project Name
Fu, Ernest                 2022 vivofit jr. 3 SKUs             1        1
                           Bounce                              1        0
                           Forerunner 255 Small                1        0
                           Forerunner 255 and 255 Music        1        0
                           Forerunner 265                      1        1
...                                                          ...      ...
Wang, Cooper               Enduro 2023                         1        1
                           Marq Hybrid                         0        0
                           fenix 7 Pro                         1        1
                           fenix 7S Pro                        1        1
                           fenix 7X Pro                        1        1

                                                         Global/Asia  \
Develop  Product QE (DPQE) Project Name
Fu, Ernest                 2022 vivofit jr. 3 SKUs                 1
                           Bounce                                  1
                           Forerunner 255 Small                    1
                           Forerunner 255 and 255 Music            1
                           Forerunner 265                          1
...                                                              ...
Wang, Cooper               Enduro 2023                             1
                           Marq Hybrid                             1
                           fenix 7 Pro                             1
                           fenix 7S Pro                            1
                           fenix 7X Pro                            1

                                                         PDP/Form107
Develop  Product QE (DPQE) Project Name
Fu, Ernest                 2022 vivofit jr. 3 SKUs                 1
                           Bounce                                  1
                           Forerunner 255 Small                    1
                           Forerunner 255 and 255 Music            1
                           Forerunner 265                          1
...                                                              ...
Wang, Cooper               Enduro 2023                             1
                           Marq Hybrid                             1
                           fenix 7 Pro                             1
                           fenix 7S Pro                            1
                           fenix 7X Pro                            1

[94 rows x 7 columns]